apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-vp.fullname" . }}
  labels: {{- include "cf-vp.provisionerLabels" . | nindent 4 }}
  {{/*  annotations:*/}}
  {{/*    {{ range $key, $value := .Values.Storage.VolumeProvisioner.ServiceAccount.Annotations }}*/}}
  {{/*    {{ $key }}: {{ $value }}*/}}
  {{/*  {{ end }}*/}}
