{{- if and .Values.monitor.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cf-monitor.fullname" . }}
  labels: {{- include "cf-monitor.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cf-monitor.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cf-monitor.fullname" . }}
  {{- end }}
