{{- if and .Values.monitor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-monitor.rollbackFullname" . }}
  labels: {{- include "cf-monitor.labels" . | nindent 4 }}
  {{/*  annotations:*/}}
  {{/*    {{ range $key, $value := .Values.Monitor.ServiceAccount.Annotations }}*/}}
  {{/*    {{ $key }}: {{ $value }}*/}}
  {{/*  {{ end }}*/}}
  {{- end }}
