{{- if not .Values.monitor.existingTokenSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: codefresh-monitor-token
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "cf-monitor.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.monitor.token  | b64enc | quote }}
{{- end }}