kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cf-venona.fullname" . }}
  labels: {{- include "cf-venona.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cf-venona.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "cf-venona.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
