apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "cf-venona.fullname" . }}
  labels: {{- include "cf-venona.labels" . | nindent 4 }}
data:
  codefresh.token: {{ .Values.global.agentToken | b64enc }}
