{{ if .Values.appProxy.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-app-proxy.fullname" . }}
  labels: {{- include "cf-app-proxy.labels" . | nindent 4 }}
  {{/*  annotations:*/}}
  {{/*    {{ range $key, $value := .Values.AppProxy.ServiceAccount.Annotations }}*/}}
  {{/*    {{ $key }}: {{ $value | quote | unescape }}*/}}
  {{/*  {{ end }}*/}}

  {{ end }}